apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: opencode-config
  namespace: developer
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    creationPolicy: Owner
    template:
      type: Opaque
      engineVersion: v2
      data:
        config: |
          {
            "$schema": "https://opencode.ai/config.json",
            "provider": {},
            "mcp": {
              "home-assistant": {
                "enabled": true,
                "type": "remote",
                "url": "http://homeassistant.home.svc.cluster.local:8123/mcp_server/sse",
                "headers": {
                  "Authorization": "Bearer {{ .ha_token }}"
                }
              },
              "kubernetes": {
                "enabled": true,
                "type": "local",
                "command": [
                  "npx",
                  "-y",
                  "kubernetes-mcp-server",
                  "--disable-destructive"
                ]
              }
            }
          }
  data:
    - secretKey: ha_token
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: homeassistant
        property: token
