apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: opencode-config
  namespace: developer
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    creationPolicy: Owner
    template:
      type: Opaque
      engineVersion: v2
      data:
        config: |
          {
            "$schema": "https://opencode.ai/config.json",
            "provider": {},
            "mcp": {
              "home-assistant": {
                "enabled": true,
                "type": "remote",
                "url": "{{ .ha_mcp_url }}"
              },
              "kubernetes": {
                "enabled": true,
                "type": "local",
                "command": [
                  "npx",
                  "-y",
                  "kubernetes-mcp-server",
                  "--disable-destructive"
                ]
              }
            }
          }
  data:
    - secretKey: ha_mcp_url
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: homeassistant
        property: mcp_url
