apiVersion: v1
kind: Service
metadata:
  name: homeassistant
  namespace: home
spec:
  selector:
    app: homeassistant
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8123
