apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opencode-data
  namespace: developer
spec:
  volumeMode: Filesystem
  storageClassName: ceph-block-replicated
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
