apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: opencode-config
  namespace: developer
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        config: |
          {
            "$schema": "https://opencode.ai/config.json",
            "provider": {
              "anthropic": {
                "options": {
                  "baseURL": "https://gateway.ai.cloudflare.com/v1/{{ .account_id }}/{{ .gateway_name }}/anthropic"
                }
              },
              "openai": {
                "options": {
                  "baseURL": "https://gateway.ai.cloudflare.com/v1/{{ .account_id }}/{{ .gateway_name }}/openai"
                }
              },
              "google": {
                "options": {
                  "baseURL": "https://gateway.ai.cloudflare.com/v1/{{ .account_id }}/{{ .gateway_name }}/google-ai-studio"
                }
              }
            }
          }
  data:
    - secretKey: account_id
      remoteRef:
        key: cloudflare-ai-gateway
        property: account-id
    - secretKey: gateway_name
      remoteRef:
        key: cloudflare-ai-gateway
        property: gateway-name
