apiVersion: v1
kind: ConfigMap
metadata:
  name: change-storage-class-config
  namespace: velero
  labels:
    velero.io/plugin-config: ""
    velero.io/change-storage-class: RestoreItemAction
data:
  ceph-danger-block: ceph-block
  ceph-safe-block: ceph-block-replicated
  safe-ceph-object: ceph-object-replicated
