apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperclip-data
  namespace: developer
spec:
  volumeMode: Filesystem
  storageClassName: ceph-safe-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
