apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperclip-config
  namespace: developer
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    creationPolicy: Owner
    template:
      type: Opaque
      engineVersion: v2
      data:
        better_auth_secret: "{{ .better_auth_secret }}"
  data:
    - secretKey: better_auth_secret
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: paperclip
        property: better_auth_secret
