apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lidarr-downloads
  namespace: download
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  volumeName: lidarr-downloads
  resources:
    requests:
      storage: 1Mi
