apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: rook-ceph

namespace: rook-ceph

helmCharts:
  - name: rook-ceph
    repo: https://charts.rook.io/release
    releaseName: rook-ceph
    namespace: rook-ceph
    version: v1.19.3
    valuesFile: ./values.yaml

resources:
  - https://github.com/rook/rook/raw/v1.19.3/deploy/examples/toolbox-operator-image.yaml
  - ./resources/ceph-block-pool.yaml
  - ./resources/ceph-block-pool-replicated.yaml
  - ./resources/ceph-cluster.yaml
  - ./resources/ceph-object-store-replicated.yaml
  - ./resources/http-route.yaml
  - ./resources/namespace.yaml
  - ./resources/storage-class-ceph-block.yaml
  - ./resources/storage-class-ceph-block-replicated.yaml
  - ./resources/storage-class-ceph-object-replicated.yaml
