apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-downloads
  namespace: download
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  volumeName: download-sonarr-downloads
  resources:
    requests:
      storage: 1Mi
