global:
  cloud: others
  clusterName: btkostner
  deploymentEnvironment: production

otelCollectorEndpoint: http://signoz-otel-collector:4317

otelInsecure: true

presets:
  otlpExporter:
    enabled: true
  loggingExporter:
    enabled: false
  logsCollection:
    enabled: true
    include:
      - /var/log/pods/*/*/*.log
    startAt: beginning
    includeFilePath: true
    includeFileName: false
  hostMetrics:
    enabled: true
    collectionInterval: 30s
    scrapers:
      cpu: {}
      disk: {}
      load: {}
      filesystem: {}
      memory: {}
      network: {}
      paging: {}
      process:
        mute_process_name_error: true
        mute_process_exe_error: true
        mute_process_io_error: true
  kubernetesAttributes:
    enabled: true
  kubeletMetrics:
    enabled: true
    collectionInterval: 30s
  k8sClusterReceiver:
    enabled: true
    collectionInterval: 30s

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi
