apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: weaver-download
  namespace: download
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  volumeName: download-weaver-download
  resources:
    requests:
      storage: 1Mi
