{
 "title": "Sonarr",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  { "title": "Runtime", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "nomad_client_allocs_cpu_total_percent{task=\"sonarr\", consul_service=\"nomad-clients\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expression": "$A / $B", "type": "math" }
   ]
  },
  { "title": "Library", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Amounts",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 18, "x": 0, "y": 13 },
   "targets": [
    { "expr": "sonarr_episode_total", "legendFormat": "Total" },
    { "expr": "sonarr_episode_missing_total", "legendFormat": "Missing" },
    {}
   ]
  },
  {
   "title": "Size",
   "type": "stat",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sonarr_series_filesize_bytes", "legendFormat": "__auto" }
   ]
  }
 ]
}