alloy:
  configMap:
    create: false
    name: alloy
    key: config.alloy
  clustering:
    enabled: true
  securityContext:
    runAsUser: 0
    capabilities:
      add:
        - BPF
        - SYS_PTRACE
        - NET_RAW
        - DAC_READ_SEARCH
        - CHECKPOINT_RESTORE
        - PERFMON
      drop:
        - ALL
  mounts:
    dockercontainers: true
    extra:
      - name: host-rootfs
        mountPath: /host/fs
        readOnly: true
      - name: host-procfs
        mountPath: /host/proc
        readOnly: true
      - name: host-sysfs
        mountPath: /host/sys
        readOnly: true
      - name: host-udev
        mountPath: /host/udev
        readOnly: true
      - name: cgroup
        mountPath: /sys/fs/cgroup
        readOnly: true
      - name: debugfs
        mountPath: /sys/kernel/debug
        readOnly: true
      - name: bpffs
        mountPath: /sys/fs/bpf
        readOnly: true
      - name: beyla
        mountPath: /var/run/beyla
    varlog: true
  stabilityLevel: experimental
controller:
  type: daemonset
  hostPID: true
  volumes:
    extra:
      - name: host-rootfs
        hostPath:
          path: /
      - name: host-procfs
        hostPath:
          path: /proc
      - name: host-sysfs
        hostPath:
          path: /sys
      - name: host-udev
        hostPath:
          path: /run/udev/data
      - name: cgroup
        hostPath:
          path: /sys/fs/cgroup
      - name: debugfs
        hostPath:
          path: /sys/kernel/debug
      - name: bpffs
        hostPath:
          path: /sys/fs/bpf
      - name: beyla
        emptyDir: {}
serviceMonitor:
  enabled: true
