apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-config
  namespace: networking
spec:
  volumeMode: Filesystem
  storageClassName: ceph-safe-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
