apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: matter-server-data
  namespace: home
spec:
  volumeMode: Filesystem
  storageClassName: ceph-safe-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
