apiVersion: v1
kind: Service
metadata:
  name: matter-server
  namespace: home
  annotations:
    lbipam.cilium.io/ips: 192.168.3.63
spec:
  selector:
    app: matter-server
  ports:
    - name: ws
      port: 5580
      protocol: TCP
      targetPort: 5580
