apiVersion: v1
kind: Service
metadata:
  name: matter-server
  namespace: home
spec:
  selector:
    app: matter-server
  ports:
    - name: ws
      port: 5580
      protocol: TCP
      targetPort: 5580
