apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: ddns

namespace: networking

resources:
  - ./resources/deployment-abraxis-tv.yaml
  - ./resources/deployment-btkostner-network.yaml
  - ./resources/secret-abraxis-tv-config.yaml
  - ./resources/secret-btkostner-network-config.yaml
