apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scryer-data
  namespace: download
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  volumeName: download-scryer-data
  resources:
    requests:
      storage: 1Mi
