name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  Lint:
    runs-on: ubuntu-slim

    steps:
      - name: Checkout
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      - name: Install
        uses: jdx/mise-action@c1ecc8f748cd28cdeabf76dab3cccde4ce692fe4 # v4.0.0

      - name: Lint
        run: mise lint
