name: Docs

on:
  push:
    branches:
      - main
    paths:
      - book.toml
      - "**/*.md"

jobs:
  Publish:
    environment:
      name: Docs
      url: https://infrastructure.btkostner.io

    permissions:
      actions: read
      contents: read
      pages: write
      id-token: write

    runs-on: ubuntu-slim

    steps:
      - name: Checkout
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      - name: Install
        uses: jdx/mise-action@c1ecc8f748cd28cdeabf76dab3cccde4ce692fe4 # v4.0.0

      - name: Build
        run: mise docs:build

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@7b1f4a764d45c48632c6b24a0339c27f5614fb0b # v4.0.0
        with:
          path: ./book

      - name: Deploy
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5.0.0
